apiVersion: v1
kind: PersistentVolume
metadata:
 name: {{ .Release.Name }}-pv
 labels:
   type: nfs
spec:
 capacity:
  storage: 50Gi
 volumeMode: Filesystem
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: {{ .Values.storage.fss_path }}
  server: {{ .Values.storage.fss_name }}
 mountOptions:
  - nconnect=16

