apiVersion: v1
kind: PersistentVolume
metadata:
 name: fss-pv
 labels:
   type: nfs
spec:
 capacity:
  storage: 50Gi
 volumeMode: Filesystem
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: /data
  server: fs1.fss.zone
 mountOptions:
  - nconnect=16

