# If your default LB is a public one, and you also want to expose Traefik internally through an additional NLB, these are the configurations

ports:
  private-web:
    # Ports must be different
    port: 8001
    expose:
      default: false    # do not expose on the default that is public
      internal: true    # this entrypoint is exposed to the internal additional service
    exposedPort: 80
    redirections:
      entryPoint:
        to: private-websecure
        scheme: https
  private-websecure:
    # Ports must be different
    port: 8444
    expose:
      default: false
      internal: true
    exposedPort: 443
    # Traefik will need to handle TLS termination for private network load balancers
    tls:
      enabled: true

service:
  additionalServices:
    internal:
      type: LoadBalancer
      annotations:
        oci.oraclecloud.com/load-balancer-type: "nlb"
        # Always specify the NLB to be internal, or creation will fail
        oci-network-load-balancer.oraclecloud.com/internal: "true"

        # Specify a private subnet OCID where to create the NLB. MUST BE SET IF THE DEFAULT LB SUBNET FOR OKE IS PUBLIC!
        # oci-network-load-balancer.oraclecloud.com/subnet: "ocid1.subnet.oc1..."

        # Better to attach 2 NSGs, one containing only ingress rules, the other containing only egress rules
        oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "ocid1.networksecuritygroup.oc1...,ocid1.networksecuritygroup.oc1..."
        # By setting this to None, you will be in charge of writing all the security rules, CCM will not be allowed to set automatically any security rule
        oci.oraclecloud.com/security-rule-management-mode: "None"

        # Defaults to FIVE_TUPLE, other values are TWO_TUPLE and THREE_TUPLE
        #oci-network-load-balancer.oraclecloud.com/backend-policy: "FIVE_TUPLE"

        # Pods as Backends configuration: health check
        oci-network-load-balancer.oraclecloud.com/health-check: '{"protocol": "HTTP", "port": 8080, "urlPath": "/healthz", "returnCode": 200, "retries": 3, "timeoutInMillis": 2000}'

        # If needed, you can reserve and assign a private IP address
        #oci-network-load-balancer.oraclecloud.com/assigned-private-ipv4: "<ipv4-address>"

        # Default value is true. Set this to false if you do not want to preserve source IP address or if you need proxy protocol
        #oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"

        # Enable proxy protocol for IP preservation. NOTE: oci-network-load-balancer.oraclecloud.com/is-preserve-source must be explicitly set to false for this to work
        #oci-network-load-balancer.oraclecloud.com/is-ppv2-enabled: "true"
      spec:
        # We are forced to put Cluster here because of the risk of packet drops when a readiness gate is implemented.
        # Example: LB health check is OK before readiness, the packet will be forwarded, but the ingress is still not available from a Kubernetes perspective.
        # Then, if the externalTrafficPolicy is Local, the packet will just be dropped, instead of being re-routed to an ingress pod in another node
        externalTrafficPolicy: "Cluster"
        # Necessary for Pods as Backends
        allocateLoadBalancerNodePorts: false