version: 0.1             
component: build
timeoutInSeconds: 5000
shell: bash
env:
  exportedVariables:
    - buildId
steps:
  - type: Command
    command: |
      buildId=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-6 | rev`
      echo "Build ID: $buildId"
  - type: Command
    command: |
      # This replaces the default open-jdk
      export GRAALVM_VERSION="21"
      export JAVA_VERSION="17"
      yum -y install graalvm${GRAALVM_VERSION}-ee-${JAVA_VERSION}-jdk;
      export JAVA_HOME=/usr/lib64/graalvm/graalvm${GRAALVM_VERSION}-ee-java${JAVA_VERSION};
      java -version

      mvn clean install
      
      docker build -f Dockerfile.native -t ${REGISTRY}/${NAMESPACE}/${IMAGE_NAME} .
      docker tag ${REGISTRY}/${NAMESPACE}/${IMAGE_NAME}:latest ${REGISTRY}/${NAMESPACE}/${IMAGE_NAME}:$buildId
outputArtifacts:
  - name: image-native
    type: DOCKER_IMAGE
    location: ${REGISTRY}/${NAMESPACE}/${IMAGE_NAME}